name: build

on: [push]

jobs:

  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build
      run: go build -v cmd/extraterm-wsl-proxy/extraterm-wsl-proxy.go

    - name: Test
      run: go test -v ./...

    - name: Keep the executable
      uses: actions/upload-artifact@v2
      with:
        name: extraterm-wsl-proxy
        path: extraterm-wsl-proxy
